DELETE FROM MasterFields WHERE CompanyId=5 AND (module='VendorEnquiry' OR module='VendorQuotation' OR module='PurchaseRequisition' OR module='PurchaseApproval' OR module='PurchaseOrder' OR module='GoodsReceiptNote' OR module='VendorBill' OR module='VendorPayment');

INSERT INTO MasterFields (CompanyId, module, fieldName, label, type, required, visible, isCustom, sortOrder, createdAt, updatedAt) VALUES
(5, 'VendorEnquiry', 'enquiryNumber', 'Enquiry Number', 'text', 0, 1, 0, 0, NOW(), NOW()),
(5, 'VendorEnquiry', 'enquiryDate', 'Enquiry Date', 'date', 1, 1, 0, 1, NOW(), NOW()),
(5, 'VendorEnquiry', 'VendorId', 'Vendor', 'relation', 1, 1, 0, 2, NOW(), NOW()),
(5, 'VendorEnquiry', 'contactPerson', 'Contact Person', 'text', 0, 1, 0, 3, NOW(), NOW()),
(5, 'VendorEnquiry', 'mobileNumber', 'Mobile Number', 'text', 0, 1, 0, 4, NOW(), NOW()),
(5, 'VendorEnquiry', 'email', 'Email', 'text', 0, 1, 0, 5, NOW(), NOW()),
(5, 'VendorEnquiry', 'productService', 'Product/Service', 'text', 0, 1, 0, 6, NOW(), NOW()),
(5, 'VendorEnquiry', 'quantity', 'Quantity', 'number', 0, 1, 0, 7, NOW(), NOW()),
(5, 'VendorEnquiry', 'expectedClosingDate', 'Expected Closing Date', 'date', 0, 1, 0, 8, NOW(), NOW()),
(5, 'VendorEnquiry', 'AssignedToId', 'Assigned To', 'relation', 0, 1, 0, 9, NOW(), NOW()),
(5, 'VendorEnquiry', 'priority', 'Priority', 'select', 0, 1, 0, 10, NOW(), NOW()),
(5, 'VendorEnquiry', 'status', 'Status', 'select', 1, 1, 0, 11, NOW(), NOW()),
(5, 'VendorEnquiry', 'estimatedValue', 'Estimated Value', 'number', 0, 1, 0, 12, NOW(), NOW()),
(5, 'VendorEnquiry', 'details', 'Details', 'textarea', 0, 1, 0, 13, NOW(), NOW()),

(5, 'VendorQuotation', 'quotationNumber', 'Quotation Number', 'text', 0, 1, 0, 0, NOW(), NOW()),
(5, 'VendorQuotation', 'quotationDate', 'Quotation Date', 'date', 1, 1, 0, 1, NOW(), NOW()),
(5, 'VendorQuotation', 'VendorId', 'Vendor', 'relation', 1, 1, 0, 2, NOW(), NOW()),
(5, 'VendorQuotation', 'VendorEnquiryId', 'Linked Enquiry', 'relation', 0, 1, 0, 3, NOW(), NOW()),
(5, 'VendorQuotation', 'validityDate', 'Validity Date', 'date', 0, 1, 0, 4, NOW(), NOW()),
(5, 'VendorQuotation', 'status', 'Status', 'select', 1, 1, 0, 5, NOW(), NOW()),
(5, 'VendorQuotation', 'termsConditions', 'Terms & Conditions', 'textarea', 0, 1, 0, 6, NOW(), NOW()),
(5, 'VendorQuotation', 'remarks', 'Remarks', 'textarea', 0, 1, 0, 7, NOW(), NOW()),
(5, 'VendorQuotation', 'totalAmount', 'Total Amount', 'number', 1, 1, 0, 8, NOW(), NOW()),

(5, 'PurchaseRequisition', 'requisitionNumber', 'Requisition Number', 'text', 0, 1, 0, 0, NOW(), NOW()),
(5, 'PurchaseRequisition', 'requisitionDate', 'Requisition Date', 'date', 1, 1, 0, 1, NOW(), NOW()),
(5, 'PurchaseRequisition', 'RequestedById', 'Requested By', 'relation', 1, 1, 0, 2, NOW(), NOW()),
(5, 'PurchaseRequisition', 'DepartmentId', 'Department', 'relation', 0, 1, 0, 3, NOW(), NOW()),
(5, 'PurchaseRequisition', 'WarehouseId', 'Warehouse', 'relation', 0, 1, 0, 4, NOW(), NOW()),
(5, 'PurchaseRequisition', 'requiredDate', 'Required Date', 'date', 0, 1, 0, 5, NOW(), NOW()),
(5, 'PurchaseRequisition', 'priority', 'Priority', 'select', 1, 1, 0, 6, NOW(), NOW()),
(5, 'PurchaseRequisition', 'status', 'Status', 'select', 1, 1, 0, 7, NOW(), NOW()),
(5, 'PurchaseRequisition', 'items', 'Items', 'json', 1, 1, 0, 8, NOW(), NOW()),
(5, 'PurchaseRequisition', 'remarks', 'Remarks', 'textarea', 0, 1, 0, 9, NOW(), NOW()),

(5, 'PurchaseApproval', 'approvalCode', 'Approval Code', 'text', 0, 1, 0, 0, NOW(), NOW()),
(5, 'PurchaseApproval', 'module', 'Module', 'select', 1, 1, 0, 1, NOW(), NOW()),
(5, 'PurchaseApproval', 'referenceId', 'Reference ID', 'text', 1, 1, 0, 2, NOW(), NOW()),
(5, 'PurchaseApproval', 'referenceType', 'Reference Type', 'text', 1, 1, 0, 3, NOW(), NOW()),
(5, 'PurchaseApproval', 'currentLevel', 'Current Level', 'number', 1, 1, 0, 4, NOW(), NOW()),
(5, 'PurchaseApproval', 'totalLevels', 'Total Levels', 'number', 1, 1, 0, 5, NOW(), NOW()),
(5, 'PurchaseApproval', 'status', 'Status', 'select', 1, 1, 0, 6, NOW(), NOW()),
(5, 'PurchaseApproval', 'approvers', 'Approvers', 'json', 1, 1, 0, 7, NOW(), NOW()),
(5, 'PurchaseApproval', 'initiatedBy', 'Initiated By', 'relation', 1, 1, 0, 8, NOW(), NOW()),
(5, 'PurchaseApproval', 'decision', 'Decision', 'select', 0, 1, 0, 9, NOW(), NOW()),
(5, 'PurchaseApproval', 'comments', 'Comments', 'textarea', 0, 1, 0, 10, NOW(), NOW()),

(5, 'PurchaseOrder', 'poNumber', 'PO Number', 'text', 0, 1, 0, 0, NOW(), NOW()),
(5, 'PurchaseOrder', 'poDate', 'PO Date', 'date', 1, 1, 0, 1, NOW(), NOW()),
(5, 'PurchaseOrder', 'VendorId', 'Vendor', 'relation', 1, 1, 0, 2, NOW(), NOW()),
(5, 'PurchaseOrder', 'VendorQuotationId', 'Vendor Quotation', 'relation', 0, 1, 0, 3, NOW(), NOW()),
(5, 'PurchaseOrder', 'PurchaseRequisitionId', 'Purchase Requisition', 'relation', 0, 1, 0, 4, NOW(), NOW()),
(5, 'PurchaseOrder', 'WarehouseId', 'Warehouse', 'relation', 0, 1, 0, 5, NOW(), NOW()),
(5, 'PurchaseOrder', 'expectedDate', 'Expected Delivery', 'date', 0, 1, 0, 6, NOW(), NOW()),
(5, 'PurchaseOrder', 'paymentTerms', 'Payment Terms', 'text', 0, 1, 0, 7, NOW(), NOW()),
(5, 'PurchaseOrder', 'status', 'Status', 'select', 1, 1, 0, 8, NOW(), NOW()),
(5, 'PurchaseOrder', 'items', 'Items', 'json', 1, 1, 0, 9, NOW(), NOW()),
(5, 'PurchaseOrder', 'totalAmount', 'Total Amount', 'number', 1, 1, 0, 10, NOW(), NOW()),
(5, 'PurchaseOrder', 'remarks', 'Remarks', 'textarea', 0, 1, 0, 11, NOW(), NOW()),

(5, 'GoodsReceiptNote', 'grnNumber', 'GRN Number', 'text', 0, 1, 0, 0, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'grnDate', 'GRN Date', 'date', 1, 1, 0, 1, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'PurchaseOrderId', 'Purchase Order', 'relation', 1, 1, 0, 2, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'WarehouseId', 'Warehouse', 'relation', 1, 1, 0, 3, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'VendorId', 'Vendor', 'relation', 1, 1, 0, 4, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'challanNumber', 'Challan Number', 'text', 0, 1, 0, 5, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'challanDate', 'Challan Date', 'date', 0, 1, 0, 6, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'transporter', 'Transporter', 'text', 0, 1, 0, 7, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'vehicleNo', 'Vehicle No', 'text', 0, 1, 0, 8, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'status', 'Status', 'select', 1, 1, 0, 9, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'items', 'Items', 'json', 1, 1, 0, 10, NOW(), NOW()),
(5, 'GoodsReceiptNote', 'remarks', 'Remarks', 'textarea', 0, 1, 0, 11, NOW(), NOW()),

(5, 'VendorBill', 'billNumber', 'Bill Number', 'text', 0, 1, 0, 0, NOW(), NOW()),
(5, 'VendorBill', 'billDate', 'Bill Date', 'date', 1, 1, 0, 1, NOW(), NOW()),
(5, 'VendorBill', 'VendorId', 'Vendor', 'relation', 1, 1, 0, 2, NOW(), NOW()),
(5, 'VendorBill', 'PurchaseOrderId', 'Purchase Order', 'relation', 0, 1, 0, 3, NOW(), NOW()),
(5, 'VendorBill', 'GRNId', 'GRN', 'relation', 0, 1, 0, 4, NOW(), NOW()),
(5, 'VendorBill', 'dueDate', 'Due Date', 'date', 0, 1, 0, 5, NOW(), NOW()),
(5, 'VendorBill', 'billAmount', 'Bill Amount', 'number', 1, 1, 0, 6, NOW(), NOW()),
(5, 'VendorBill', 'taxAmount', 'Tax Amount', 'number', 0, 1, 0, 7, NOW(), NOW()),
(5, 'VendorBill', 'totalAmount', 'Total Amount', 'number', 1, 1, 0, 8, NOW(), NOW()),
(5, 'VendorBill', 'status', 'Status', 'select', 1, 1, 0, 9, NOW(), NOW()),
(5, 'VendorBill', 'paymentStatus', 'Payment Status', 'select', 1, 1, 0, 10, NOW(), NOW()),
(5, 'VendorBill', 'remarks', 'Remarks', 'textarea', 0, 1, 0, 11, NOW(), NOW()),

(5, 'VendorPayment', 'paymentNumber', 'Payment Number', 'text', 0, 1, 0, 0, NOW(), NOW()),
(5, 'VendorPayment', 'paymentDate', 'Payment Date', 'date', 1, 1, 0, 1, NOW(), NOW()),
(5, 'VendorPayment', 'VendorId', 'Vendor', 'relation', 1, 1, 0, 2, NOW(), NOW()),
(5, 'VendorPayment', 'VendorBillId', 'Vendor Bill', 'relation', 0, 1, 0, 3, NOW(), NOW()),
(5, 'VendorPayment', 'amount', 'Amount', 'number', 1, 1, 0, 4, NOW(), NOW()),
(5, 'VendorPayment', 'mode', 'Payment Mode', 'select', 1, 1, 0, 5, NOW(), NOW()),
(5, 'VendorPayment', 'referenceNumber', 'Reference Number', 'text', 0, 1, 0, 6, NOW(), NOW()),
(5, 'VendorPayment', 'bankName', 'Bank Name', 'text', 0, 1, 0, 7, NOW(), NOW()),
(5, 'VendorPayment', 'chequeDate', 'Cheque Date', 'date', 0, 1, 0, 8, NOW(), NOW()),
(5, 'VendorPayment', 'clearingDate', 'Clearing Date', 'date', 0, 1, 0, 9, NOW(), NOW()),
(5, 'VendorPayment', 'status', 'Status', 'select', 1, 1, 0, 10, NOW(), NOW()),
(5, 'VendorPayment', 'remarks', 'Remarks', 'textarea', 0, 1, 0, 11, NOW(), NOW());
