apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: thinktech

spec:

  selector:
    app: thinktech-backend

  ports:

  - port: 5000

    targetPort: 5000

  type: ClusterIP
