apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: thinktech
data:
  PORT: "5000"
  NODE_ENV: "production"

  DB_HOST: "34.100.211.48"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_NAME: "thinktech_crm"

  SMTP_HOST: "mail.vetansutra.com"
  SMTP_PORT: "465"
  SMTP_SECURE: "true"
  SMTP_USER: "info@vetansutra.com"
  EMAIL_FROM_NAME: "Thinktech Software"
  EMAIL_FROM_ADDRESS: "info@vetansutra.com"
